// MUI sx styles owned by public-site components.
export const websiteSx = {
  'sb-story-title': {},
  'sb-mobile-login': {},
  'sb-header': {
    height: '104px',
    backgroundColor: '#000',
    backdropFilter: 'none',
    WebkitBackdropFilter: 'none',
    color: '#fff',
    position: 'sticky',
    top: '0',
    zIndex: '40',
    willChange: 'auto',
    transition: 'none',
  },
  'sb-header-overlay': {
    marginBottom: '-104px',
  },
  'sb-header-transparent': {
    backgroundColor: 'rgba(12, 14, 12, 0)',
    backdropFilter: 'none',
    WebkitBackdropFilter: 'none',
    boxShadow: 'none',
  },
  'sb-nav': {
    width: '100%',
    padding: '12px var(--sb-gutter)',
    height: '72px',
    margin: 'auto',
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    gap: '30px',
  },
  'sb-topbar': {
    height: '32px',
    padding: '0 var(--sb-gutter)',
    background: '#000',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid rgba(255,255,255,.12)',
    color: 'rgba(255,255,255,.68)',
    font: '500 10px/1 var(--font-kanit), sans-serif',
    letterSpacing: '.025em',
    '& .sb-topbar-contact': {
      height: '100%',
      display: 'flex',
      alignItems: 'center',
      gap: '14px',
      color: 'var(--sb-gold)',
      '& .sb-topbar-social': {
        width: '15px',
        height: '15px',
        display: 'inline-flex',
        flex: '0 0 15px',
        alignItems: 'center',
        justifyContent: 'center',
      },
      '& img': {
        width: '15px',
        height: '15px',
        display: 'block',
        objectFit: 'contain',
      },
      '& .sb-topbar-phone': {
        width: 'auto',
        height: 'auto',
        display: 'inline-block',
        flex: '0 0 auto',
        whiteSpace: 'nowrap',
        color: '#f2f0e9',
        font: '600 10px/1 var(--font-inter), sans-serif',
        letterSpacing: '.04em',
        transition: 'color 180ms ease',
      },
      '& a:hover': { color: 'var(--sb-gold)' },
    },
    '@media (max-width: 600px)': {
      '& > span': { display: 'none' },
      '& .sb-topbar-contact': { marginLeft: 'auto', gap: '12px' },
    },
  },
  'sb-brand': {
    display: 'flex',
    alignItems: 'center',
    gap: '11px',
    color: 'var(--sb-gold)',
    font: '700 13px/0.92 var(--font-inter),\n    sans-serif',
    letterSpacing: '0.05em',
    whiteSpace: 'nowrap',
    minWidth: '170px',
    '@media (max-width: 600px)': {
      minWidth: '0',
    },
  },
  'sb-nav-links': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 'clamp(17px, 2.1vw, 38px)',
    position: 'absolute',
    left: '50%',
    transform: 'translateX(-50%)',
    '& a': {
      fontSize: '13px',
      color: '#e2e3de',
      height: '72px',
      display: 'flex',
      alignItems: 'center',
      position: 'relative',
      whiteSpace: 'nowrap',
      transition: 'color 200ms ease',
      '&::after': {
        content: "''",
        position: 'absolute',
        left: '0',
        bottom: '20px',
        width: '0',
        height: '1px',
        background: 'var(--sb-gold)',
        transition: 'width 220ms ease',
      },
    },
    '& a:hover': {
      color: 'var(--sb-gold)',
    },
    '& a:hover::after': { width: '100%' },
    "& a[aria-current='page']": {
      color: 'var(--sb-gold)',
    },
    "& a[aria-current='page']:after": {
      width: '100%',
    },
    '@media (max-width: 1100px)': {
      display: 'none',
    },
  },
  'sb-nav-action': {
    marginLeft: '-18px',
    fontSize: '13px',
    color: 'var(--sb-black)',
    border: '1px solid var(--sb-gold)',
    borderRadius: '10px',
    padding: '9px 16px',
    background: 'var(--sb-gold)',
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    whiteSpace: 'nowrap',
    transition: 'background 180ms ease, border-color 180ms ease',
    '&:hover': {
      color: 'var(--sb-black)',
      background: '#e1bf80',
      borderColor: '#e1bf80',
    },
    '& svg': {
      display: 'block',
      width: '17px',
      height: '17px',
    },
    '@media (max-width: 1100px)': {
      display: 'none',
    },
  },
  'sb-nav-login': {
    marginLeft: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '40px',
    padding: '0 19px',
    border: '1px solid rgba(226, 227, 222, 0.55)',
    borderRadius: '10px',
    background: 'rgba(255, 255, 255, 0.03)',
    color: '#e2e3de',
    fontSize: '12px',
    whiteSpace: 'nowrap',
    transition:
      'background 180ms ease, border-color 180ms ease, color 180ms ease',
    '&:hover': {
      borderColor: '#fff',
      color: 'var(--sb-black)',
      background: '#fff',
    },
    '@media (max-width: 1100px)': {
      display: 'none',
    },
  },
  'sb-language-switcher': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '5px',
    minHeight: '40px',
    padding: '0 12px',
    border: '1px solid rgba(226, 227, 222, 0.55)',
    borderRadius: '10px',
    background: 'rgba(255, 255, 255, 0.03)',
    color: 'rgba(226, 227, 222, 0.58)',
    cursor: 'pointer',
    fontFamily: 'var(--font-kanit), sans-serif',
    fontSize: '12px',
    lineHeight: '1',
    transition:
      'background 180ms ease, border-color 180ms ease, color 180ms ease',
    '& span.active': {
      color: '#fff',
      fontWeight: '700',
    },
    '& i': {
      color: 'rgba(226, 227, 222, 0.38)',
      fontStyle: 'normal',
    },
    '&:hover': {
      background: '#fff',
      borderColor: '#fff',
      color: 'rgba(23, 20, 17, 0.56)',
    },
    '&:hover span.active': {
      color: 'var(--sb-black)',
    },
    '&:hover i': {
      color: 'rgba(23, 20, 17, 0.38)',
    },
    '@media (max-width: 600px)': {
      minHeight: '36px',
      padding: '0 10px',
    },
  },
  'sb-mobile-cta': {
    '& svg': {
      display: 'block',
      width: '17px',
      height: '17px',
    },
  },
  'sb-menu-toggle': {
    display: 'none',
    marginLeft: 'auto',
    background: 'transparent',
    border: '0',
    width: '40px',
    height: '40px',
    cursor: 'pointer',
    padding: '10px',
    '& span': {
      display: 'block',
      height: '1.5px',
      background: '#fff',
      margin: '5px 0',
      transition: 'transform 180ms ease,\n    opacity 180ms ease',
    },
    "&[aria-expanded='true'] span:first-child": {
      transform: 'translateY(6.5px) rotate(45deg)',
    },
    "&[aria-expanded='true'] span:nth-child(2)": {
      opacity: '0',
    },
    "&[aria-expanded='true'] span:last-child": {
      transform: 'translateY(-6.5px) rotate(-45deg)',
    },
    '@media (max-width: 1100px)': {
      display: 'block',
    },
  },
  'sb-mobile-nav': {
    display: 'none',
    '@media (max-width: 1100px)': {
      display: 'flex',
      position: 'absolute',
      top: '104px',
      left: '0',
      right: '0',
      minHeight: 'calc(100svh - 104px)',
      background: 'var(--sb-black)',
      padding: '25px var(--sb-gutter) 45px',
      flexDirection: 'column',
      '& > a': {
        fontSize: 'clamp(25px, 5vw, 42px)',
        borderBottom: '1px solid #3b3d36',
        padding: '15px 0',
      },
      "& > a[aria-current='page']": {
        color: 'var(--sb-gold)',
      },
      '& .sb-mobile-cta': {
        fontSize: '16px',
        color: 'var(--sb-gold)',
        marginTop: 'auto',
        borderBottom: '0',
        display: 'flex',
        justifyContent: 'space-between',
      },
      '& .sb-mobile-login': {
        border: '1px solid var(--sb-gold)',
        color: 'var(--sb-gold)',
        fontSize: '15px',
        padding: '13px 18px',
        textAlign: 'center',
        marginTop: '14px',
      },
    },
  },
  'sb-footer': {
    position: 'relative',
    overflow: 'hidden',
    background: '#000',
    color: '#fff',
  },
  'sb-footer-rail': {
    position: 'absolute',
    top: '0',
    left: '0',
    right: '0',
    height: '1px',
    background:
      'linear-gradient(90deg, transparent 0%, rgba(213, 175, 98, 0.26) 18%, var(--sb-gold) 50%, rgba(213, 175, 98, 0.26) 82%, transparent 100%)',
  },
  'sb-footer-main': {
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: 'minmax(260px, 0.86fr) minmax(560px, 1.34fr)',
    gap: 'clamp(56px, 9vw, 152px)',
    paddingBlock: 'clamp(68px, 7vw, 116px) clamp(54px, 5.5vw, 84px)',
    '@media (max-width: 1050px)': {
      gridTemplateColumns: '0.72fr 1.28fr',
      gap: 'clamp(40px, 6vw, 72px)',
    },
    '@media (max-width: 600px)': {
      gridTemplateColumns: '1fr',
      gap: '46px',
      paddingBlock: '70px 54px',
    },
  },
  'sb-footer-brand': {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    color: 'var(--sb-gold)',
    width: 'fit-content',
    '& img': {
      width: '62px',
      height: '62px',
    },
  },
  'sb-footer-brand-column': {
    minWidth: '0',
  },
  'sb-footer-brand-title': {
    font: '700 clamp(18px, 1.6vw, 24px)/1 var(--font-inter), sans-serif',
    letterSpacing: '0.035em',
    whiteSpace: 'nowrap',
  },
  'sb-footer-brand-copy': {
    maxWidth: '330px',
    marginTop: '28px',
    '& p': {
      margin: '0',
      color: 'rgba(245, 245, 240, 0.68)',
      font: '400 15px/1.75 var(--font-kanit), sans-serif',
    },
  },
  'sb-footer-branch-link': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '12px',
    marginTop: '26px',
    paddingBottom: '10px',
    borderBottom: '1px solid rgba(213, 175, 98, 0.46)',
    color: 'var(--sb-gold)',
    font: '600 13px/1 var(--font-kanit), sans-serif',
    transition: 'border-color 220ms ease, color 220ms ease',
    '& svg': {
      width: '17px',
      height: '17px',
      stroke: 'currentColor',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      strokeWidth: '1.8',
      transition: 'transform 220ms ease',
    },
    '&:hover': {
      color: '#f1cf89',
      borderColor: '#f1cf89',
    },
    '&:hover svg': { transform: 'translateX(4px)' },
  },
  'sb-footer-links': {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 'clamp(26px, 3vw, 52px)',
    '& > div': {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      gap: '13px',
    },
    '& span:first-child': {
      font: '600 11px/1 var(--font-kanit), sans-serif',
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      color: 'var(--sb-gold)',
      marginBottom: '11px',
    },
    '& a': {
      position: 'relative',
      color: 'rgba(245, 245, 240, 0.68)',
      font: '400 14px/1.35 var(--font-kanit), sans-serif',
      transition: 'color 200ms ease',
      '&::after': {
        content: "''",
        position: 'absolute',
        left: '0',
        bottom: '-4px',
        width: '0',
        height: '1px',
        background: 'var(--sb-gold)',
        transition: 'width 220ms ease',
      },
    },
    '& span:not(:first-child)': {
      color: 'rgba(245, 245, 240, 0.46)',
      font: '400 13px/1.45 var(--font-kanit), sans-serif',
    },
    '& a:hover': {
      color: 'var(--sb-gold)',
    },
    '& a:hover::after': { width: '100%' },
    '@media (max-width: 600px)': {
      gridTemplateColumns: '1fr 1fr',
      gap: '38px 26px',
      '& > div:last-child': {
        gridColumn: '1/-1',
      },
    },
  },
  'sb-footer-bottom': {
    '& a:hover': {
      color: 'var(--sb-gold)',
    },
    position: 'relative',
    borderTop: '1px solid rgba(255, 255, 255, 0.12)',
    minHeight: '78px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '30px',
    font: '500 11px var(--font-kanit), sans-serif',
    color: 'rgba(245, 245, 240, 0.43)',
    '& > div': {
      display: 'flex',
      gap: '26px',
      '& a': {
        transition: 'color 200ms ease',
      },
    },
    '@media (max-width: 600px)': {
      alignItems: 'flex-start',
      flexDirection: 'column',
      justifyContent: 'center',
      paddingBlock: '25px',
      gap: '13px',
    },
  },
  'sb-container': {
    maxWidth: '1600px',
    marginInline: 'auto',
    paddingInline: 'var(--sb-gutter)',
  },
  'sb-photo': {
    position: 'relative',
    overflow: 'hidden',
    background: '#171914',
    minWidth: '0',
    '& img': {
      objectFit: 'cover',
      transition: 'transform 0.7s cubic-bezier(0.2, 0.8, 0.2, 1)',
    },
    'a:hover > & img': {
      transform: 'scale(1.025)',
    },
  },
  'sb-rule': {
    display: 'block',
    width: '32px',
    height: '1px',
    background: 'var(--sb-gold)',
    marginBottom: '28px',
  },
  'sb-button': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '12px',
    minHeight: '52px',
    padding: '0 23px',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '1',
    transition: 'background 0.2s,\n    color 0.2s,\n    border-color 0.2s',
    cursor: 'pointer',
    border: '1px solid transparent',
    borderRadius: '10px',
    whiteSpace: 'nowrap',
    '& svg': {
      width: '19px',
      height: '19px',
      flex: 'none',
    },
    '& .sb-animated-arrow': {
      display: 'inline-flex',
      flex: 'none',
      lineHeight: '0',
    },
  },
  'sb-text-link': {
    '& svg': {
      width: '19px',
      height: '19px',
      flex: 'none',
    },
    display: 'inline-flex',
    alignItems: 'center',
    gap: '30px',
    borderBottom: '1px solid var(--sb-ink)',
    paddingBottom: '8px',
    fontSize: '14px',
    fontWeight: '600',
    whiteSpace: 'nowrap',
    '&:hover': {
      color: '#96723b',
      borderColor: '#96723b',
    },
  },
  'sb-row-link': {
    '& svg': {
      width: '19px',
      height: '19px',
      flex: 'none',
    },
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    fontSize: '14px',
    fontWeight: '600',
    whiteSpace: 'nowrap',
    '@media (max-width: 800px)': {
      gridColumn: '3',
    },
    '@media (max-width: 600px)': {
      gridColumn: '2/-1',
    },
  },
  'sb-button-gold': {
    background: 'var(--sb-gold)',
    color: 'var(--sb-black)',
    '&:hover': {
      background: '#e1bf80',
    },
  },
  'sb-button-dark': {
    background: 'var(--sb-black)',
    color: '#fff',
    '&:hover': {
      background: '#33352e',
    },
  },
  'sb-button-ghost': {
    borderColor: 'rgba(255, 255, 255, 0.62)',
    color: '#fff',
    background: 'transparent',
    '&:hover': {
      background: '#fff',
      color: 'var(--sb-black)',
      borderColor: '#fff',
    },
  },
  'sb-button-outline-light': {
    borderColor: 'rgba(255, 255, 255, 0.62)',
    color: '#fff',
    background: 'transparent',
    '&:hover': {
      background: '#fff',
      color: 'var(--sb-black)',
      borderColor: '#fff',
    },
  },
  'sb-actions': {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  'sb-home-hero': {
    height: 'clamp(640px, calc(100svh - 72px), 940px)',
    minHeight: '620px',
    position: 'relative',
    overflow: 'hidden',
    background: '#171914',
    color: '#fff',
    '& h1': {
      fontSize: 'clamp(58px, 5vw, 76px)',
      fontWeight: '400',
      lineHeight: '1.1',
      letterSpacing: '-0.05em',
      margin: '0',
      textWrap: 'balance',
      fontFamily: 'var(--font-kanit), sans-serif',
      '& .sb-hero-title-accent': {
        color: 'var(--sb-gold)',
      },
    },
    '& p': {
      maxWidth: '515px',
      fontSize: 'clamp(16px, 1.25vw, 20px)',
      lineHeight: '1.75',
      color: '#ebede8',
      margin: '30px 0 35px',
    },
    '@media (max-width: 800px)': {
      height: '700px',
      '& h1': {
        fontSize: 'clamp(50px, 8vw, 76px)',
      },
    },
    '@media (max-width: 600px)': {
      height: 'calc(100svh - 72px)',
      minHeight: '610px',
      '& h1': {
        fontSize: 'clamp(46px, 10vw, 64px)',
      },
      '& p': {
        fontSize: '15px',
        lineHeight: '1.65',
        margin: '20px 0 25px',
      },
      '& .sb-actions': {
        gap: '10px',
      },
      '& .sb-button': {
        minHeight: '47px',
        paddingInline: '15px',
        gap: '12px',
        fontSize: '12px',
      },
    },
  },
  'sb-home-hero-photo': {
    position: 'absolute',
    inset: '0',
    '& img': {
      objectPosition: 'center 55%',
    },
    '@media (max-width: 600px)': {
      '& img': {
        objectPosition: '61% center',
      },
    },
  },
  'sb-home-hero-video': {
    position: 'absolute',
    inset: '0',
    width: '100%',
    height: '100%',
    display: 'block',
    objectFit: 'cover',
    objectPosition: 'center 55%',
    '@media (max-width: 600px)': {
      objectPosition: '61% center',
    },
  },
  'sb-home-hero-shade': {
    position: 'absolute',
    inset: '0',
    background:
      'linear-gradient(\n      90deg,\n      rgba(0, 0, 0, 0.76) 0%,\n      rgba(0, 0, 0, 0.49) 37%,\n      rgba(0, 0, 0, 0.08) 75%\n    ),\n    linear-gradient(0deg, rgba(0, 0, 0, 0.2), transparent 40%)',
    '@media (max-width: 800px)': {
      background:
        'linear-gradient(90deg, rgba(0, 0, 0, 0.68), rgba(0, 0, 0, 0.15)),\n      linear-gradient(0deg, rgba(0, 0, 0, 0.18), transparent 60%)',
    },
    '@media (max-width: 600px)': {
      background:
        'linear-gradient(\n      0deg,\n      rgba(0, 0, 0, 0.72),\n      rgba(0, 0, 0, 0.42) 55%,\n      rgba(0, 0, 0, 0.1)\n    )',
    },
  },
  'sb-home-hero-content': {
    position: 'relative',
    zIndex: '1',
    width: 'min(760px, 75vw)',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '50px 0 235px var(--sb-gutter)',
    '@media (max-width: 800px)': {
      width: 'min(680px, 95vw)',
    },
    '@media (max-width: 600px)': {
      justifyContent: 'end',
      padding: '0 var(--sb-gutter) 62px',
      width: '100%',
    },
  },
  'sb-hero-side-note': {
    position: 'absolute',
    right: 'var(--sb-gutter)',
    bottom: '220px',
    font: '600 11px var(--font-inter),\n    sans-serif',
    letterSpacing: '0.22em',
    zIndex: '1',
    '@media (max-width: 600px)': {
      display: 'none',
    },
  },
  'sb-hero-services': {
    position: 'absolute',
    zIndex: '2',
    left: 'var(--sb-gutter)',
    right: 'var(--sb-gutter)',
    bottom: '24px',
    display: 'grid',
    gridTemplateColumns: 'repeat(5, minmax(0, 1fr))',
    gap: '10px',
    height: '182px',
    '& > a': {
      minWidth: '0',
    },
    '@media (max-width: 1050px)': {
      left: '22px',
      right: '22px',
      height: '164px',
    },
    '@media (max-width: 800px)': {
      left: 'var(--sb-gutter)',
      right: '0',
      bottom: '18px',
      display: 'flex',
      gap: '10px',
      overflowX: 'auto',
      overscrollBehaviorX: 'contain',
      scrollbarWidth: 'none',
      height: '148px',
      paddingRight: 'var(--sb-gutter)',
      '&::-webkit-scrollbar': { display: 'none' },
      '& > a': {
        flex: '0 0 min(248px, 70vw)',
      },
    },
    '@media (max-width: 600px)': {
      display: 'none',
    },
  },
  'sb-hero-service-card': {
    position: 'relative',
    display: 'block',
    overflow: 'hidden',
    color: '#fff',
    background: '#0b0d0b',
    border: '1px solid rgba(208, 177, 112, 0.38)',
    borderRadius: '5px',
    boxShadow: '0 14px 35px rgba(0, 0, 0, 0.26)',
    '& .sb-photo': {
      position: 'absolute',
      inset: '0',
      height: '100%',
    },
    '& .sb-photo:after': {
      content: "''",
      position: 'absolute',
      inset: '0',
      background:
        'linear-gradient(180deg, rgba(3, 5, 4, 0.08) 0%, rgba(3, 5, 4, 0.88) 92%)',
    },
    '& .sb-hero-service-card-copy': {
      position: 'relative',
      zIndex: '1',
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'end',
      padding: '18px',
    },
    '& h2': {
      color: '#d6ae62',
      font: '700 clamp(12px, 1.05vw, 16px)/1.1 var(--font-inter), sans-serif',
      letterSpacing: '0.015em',
      margin: '0',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    '& p': {
      color: 'rgba(255, 255, 255, 0.82)',
      fontSize: '12px',
      lineHeight: '1.45',
      margin: '8px 0 12px',
    },
    '& span': {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      color: '#d6ae62',
      font: '700 10px var(--font-kanit), sans-serif',
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
    },
    '& span svg': {
      width: '14px',
      height: '14px',
    },
    '&.sb-hero-service-card-ev h2, &.sb-hero-service-card-ev span': {
      color: '#74c86a',
    },
    '&.sb-hero-service-card-bpost h2, &.sb-hero-service-card-bpost span': {
      color: '#e34b45',
    },
    '&:hover': {
      borderColor: 'rgba(222, 186, 111, 0.8)',
    },
    '&:hover img': {
      transform: 'scale(1.04)',
    },
    '@media (max-width: 1050px)': {
      '& .sb-hero-service-card-copy': { padding: '14px' },
      '& p': { display: 'none' },
      '& span': { marginTop: '8px' },
    },
  },
  'sb-hero-stats': {
    margin: 'clamp(18px, 2vw, 32px) var(--sb-gutter) clamp(58px, 6vw, 100px)',
    display: 'grid',
    gridTemplateColumns: 'repeat(6, minmax(0, 1fr))',
    background: '#000',
    border: '1px solid rgba(208, 177, 112, 0.32)',
    borderRadius: '8px',
    overflow: 'hidden',
    color: '#fff',
    '@media (max-width: 1050px)': {
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    },
    '@media (max-width: 600px)': {
      display: 'flex',
      margin: '18px var(--sb-gutter) 54px',
      overflowX: 'auto',
      scrollbarWidth: 'none',
      '&::-webkit-scrollbar': { display: 'none' },
    },
  },
  'sb-hero-stat': {
    minWidth: '0',
    minHeight: '132px',
    padding: '22px clamp(16px, 1.6vw, 28px)',
    overflow: 'hidden',
    borderRight: '1px solid rgba(255, 255, 255, 0.12)',
    transition: 'background-color 260ms ease',
    '&:last-child': { borderRight: '0' },
    '& .sb-hero-stat-content': {
      height: '100%',
      display: 'flex',
      alignItems: 'center',
      gap: '16px',
      transition: 'transform 300ms cubic-bezier(0.22, 1, 0.36, 1)',
    },
    '& .sb-stat-icon': {
      flex: '0 0 auto',
      width: '46px',
      height: '46px',
      color: 'var(--sb-gold)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      transition: 'color 220ms ease',
    },
    '& .sb-stat-icon svg': {
      width: '46px',
      height: '46px',
    },
    '& strong, & span, & p': {
      display: 'block',
      margin: '0',
      whiteSpace: 'nowrap',
    },
    '& strong': {
      color: '#fff',
      font: '700 clamp(24px, 2vw, 36px)/1 var(--font-inter), sans-serif',
      letterSpacing: '-0.04em',
    },
    '& span': {
      marginTop: '5px',
      color: 'rgba(255, 255, 255, 0.88)',
      font: '700 10px/1.2 var(--font-inter), sans-serif',
      letterSpacing: '0.04em',
    },
    '& p': {
      marginTop: '8px',
      color: 'rgba(255, 255, 255, 0.6)',
      font: '500 12px/1.2 var(--font-kanit), sans-serif',
    },
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.045)',
    },
    '&:hover .sb-hero-stat-content': {
      transform: 'scale(1.04)',
    },
    '&:hover .sb-stat-icon': {
      color: '#e4bf76',
    },
    '@media (max-width: 1050px)': {
      borderBottom: '1px solid rgba(255, 255, 255, 0.12)',
      '&:nth-of-type(3n)': { borderRight: '0' },
      '&:nth-last-of-type(-n + 3)': { borderBottom: '0' },
    },
    '@media (max-width: 600px)': {
      flex: '0 0 240px',
      minHeight: '115px',
      borderRight: '1px solid rgba(255, 255, 255, 0.12)',
      borderBottom: '0',
      '&:nth-of-type(3n)': {
        borderRight: '1px solid rgba(255, 255, 255, 0.12)',
      },
      '&:last-child': { borderRight: '0' },
    },
  },
  'sb-home-editorial': {
    background: '#000',
    padding: 'clamp(28px, 3vw, 54px) 0 clamp(48px, 5vw, 92px)',
    '& .sb-editorial-cta': {
      width: '185px !important',
      maxWidth: '100%',
      justifyContent: 'center !important',
      textAlign: 'center',
      whiteSpace: 'nowrap !important',
    },
    '& .sb-editorial-cta:hover': {
      background: '#e1bf80',
      borderColor: '#e1bf80',
      color: '#000',
    },
  },
  'sb-story-strip': {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    minHeight: 'clamp(400px, 32vw, 560px)',
    background: '#000',
    color: '#fff',
    border: '1px solid rgba(202, 164, 94, 0.42)',
    borderRadius: '20px',
    overflow: 'hidden',
    margin: '0 var(--sb-gutter) clamp(24px, 3vw, 42px)',
    '& h2': {
      fontWeight: '500',
      fontSize: 'clamp(30px, 3vw, 46px)',
      lineHeight: '1.02',
      letterSpacing: '-0.045em',
      margin: '0',
      '& span': { color: 'var(--sb-gold)' },
    },
    '& .sb-story-copy': {
      alignSelf: 'center',
      padding: '80px',
    },
    '& .sb-story-copy p': {
      maxWidth: '500px',
      margin: '22px 0 0',
      color: 'rgba(255, 255, 255, 0.72)',
      fontSize: 'clamp(14px, 1.2vw, 17px)',
      lineHeight: '1.72',
    },
    '& .sb-photo': {
      position: 'relative',
      height: '100%',
      minHeight: 'inherit',
      '&::after': {
        content: '""',
        position: 'absolute',
        inset: '0',
        zIndex: '1',
        pointerEvents: 'none',
        background:
          'linear-gradient(90deg, #000 0%, rgba(0, 0, 0, 0.92) 12%, rgba(0, 0, 0, 0.5) 30%, transparent 54%)',
      },
    },
    '@media (max-width: 800px)': {
      gridTemplateColumns: '1fr',
      minHeight: '0',
      '& .sb-story-copy': { padding: '80px' },
      '& .sb-photo': {
        minHeight: '360px',
      },
    },
    '@media (max-width: 600px)': {
      '& h2': {
        fontSize: '30px',
      },
    },
  },
  'sb-editorial-link': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 'min(100%, 300px)',
    minHeight: '64px',
    padding: '0 28px',
    marginTop: '31px',
    border: '1px solid var(--sb-gold)',
    borderRadius: '20px',
    background: 'var(--sb-gold)',
    color: '#000',
    font: '700 16px/1 var(--font-kanit), sans-serif',
    transition: 'background 180ms ease, border-color 180ms ease',
    '&:hover': { background: '#e1bf80', borderColor: '#e1bf80' },
    '& svg': { width: '18px', height: '18px' },
  },
  'sb-editorial-cta': {
    boxSizing: 'border-box',
    display: 'inline-flex',
    alignItems: 'center',
    width: 'fit-content',
    maxWidth: '100%',
    minWidth: '0',
    minHeight: '52px',
    padding: '0 23px',
    gap: '12px',
    borderRadius: '10px',
    font: '600 14px/1 var(--font-kanit), sans-serif',
    justifyContent: 'flex-start',
    '& svg': {
      width: '19px',
      height: '19px',
      flex: 'none',
    },
    '& .sb-animated-arrow': {
      display: 'inline-flex',
      flex: 'none',
      lineHeight: '0',
    },
    '& .sb-animated-arrow svg': {
      width: '19px',
      height: '19px',
    },
  },
  'sb-section-heading': {
    '& h2': {
      fontWeight: '400',
      fontSize: 'clamp(32px, 3.4vw, 58px)',
      lineHeight: '1.15',
      letterSpacing: '-0.035em',
      margin: '0',
      textWrap: 'balance',
    },
    display: 'flex',
    alignItems: 'end',
    justifyContent: 'space-between',
    gap: '40px',
    '& p': {
      margin: '16px 0 0',
      color: 'var(--sb-muted)',
      fontSize: '16px',
      lineHeight: '1.7',
    },
    '@media (max-width: 600px)': {
      '& h2': {
        fontSize: '34px',
      },
      display: 'block',
      '& .sb-text-link': {
        marginTop: '24px',
      },
    },
  },
  'sb-menu-feature': {
    '& h2': {
      fontWeight: '500',
      fontSize: 'clamp(28px, 2.6vw, 42px)',
      lineHeight: '1.02',
      letterSpacing: '-0.045em',
      margin: '0',
      '& span': { color: 'var(--sb-gold)' },
    },
    display: 'grid',
    gridTemplateColumns: 'minmax(360px, 0.72fr) minmax(640px, 1.48fr)',
    minHeight: 'clamp(390px, 30vw, 540px)',
    height: 'auto',
    background: 'var(--sb-black)',
    color: '#fff',
    border: '1px solid rgba(202, 164, 94, 0.48)',
    borderRadius: '20px',
    overflow: 'hidden',
    margin: '0 var(--sb-gutter) clamp(24px, 3vw, 42px)',
    '@media (max-width: 1100px)': {
      gridTemplateColumns: '1fr',
      '& .sb-menu-feature-mini': { display: 'none' },
    },
    '@media (max-width: 800px)': {
      height: 'auto',
      gridTemplateColumns: '1fr',
    },
    '@media (max-width: 600px)': {
      '& h2': {
        fontSize: '28px',
      },
      display: 'flex',
      flexDirection: 'column',
    },
  },
  'sb-branch-banner': {
    '& h2': {
      fontWeight: '500',
      fontSize: 'clamp(28px, 2.6vw, 42px)',
      lineHeight: '1.04',
      letterSpacing: '-0.045em',
      margin: '0',
      textWrap: 'balance',
      whiteSpace: 'nowrap',
    },
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.34fr) minmax(360px, .66fr)',
    background: '#000',
    color: '#fff',
    minHeight: 'clamp(320px, 24vw, 430px)',
    border: '1px solid rgba(202, 164, 94, .48)',
    borderRadius: '20px',
    overflow: 'hidden',
    margin: '0 var(--sb-gutter) clamp(24px, 3vw, 42px)',
    '& > .sb-photo': {
      position: 'relative',
      minHeight: 'inherit',
      '&::after': {
        content: '""',
        position: 'absolute',
        inset: '0',
        zIndex: '1',
        pointerEvents: 'none',
        background:
          'linear-gradient(90deg, transparent 22%, rgba(0,0,0,.42) 64%, #000 100%)',
      },
    },
    '& > .sb-photo img': {
      objectPosition: 'center',
    },
    '& > div:last-child': {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      padding: '80px',
      maxWidth: '620px',
      background:
        'radial-gradient(circle at 85% 20%, rgba(199,164,103,.12), transparent 39%), #000',
    },
    '& p': {
      maxWidth: '470px',
      color: '#dedfd8',
      fontSize: '16px',
      lineHeight: '1.75',
      margin: '17px 0 26px',
    },
    '& .sb-button': {
      width: 'fit-content',
      maxWidth: '100%',
      minWidth: '0',
      minHeight: '52px',
      paddingInline: '23px',
      borderRadius: '10px',
      justifyContent: 'flex-start',
      gap: '12px',
      background: 'var(--sb-gold)',
      borderColor: 'var(--sb-gold)',
      color: '#000',
      '& svg': { width: '19px', height: '19px', flex: 'none' },
    },
    '@media (max-width: 600px)': {
      gridTemplateColumns: '1fr',
      '& h2': { whiteSpace: 'normal', fontSize: '30px' },
      '& > .sb-photo': { minHeight: '300px' },
      '& > div:last-child': {
        padding: '80px',
      },
    },
  },
  'sb-franchise-preview': {
    '& h2': {
      fontWeight: '500',
      fontSize: 'clamp(29px, 2.7vw, 44px)',
      lineHeight: '1.04',
      letterSpacing: '-0.045em',
      margin: '0',
      '& span': { color: 'var(--sb-gold)' },
    },
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: '0',
    alignItems: 'center',
    minHeight: 'clamp(360px, 29vw, 520px)',
    background: '#000',
    color: '#fff',
    border: '1px solid rgba(202, 164, 94, .48)',
    borderRadius: '20px',
    overflow: 'hidden',
    margin: '0 var(--sb-gutter)',
    '& > div:first-child': {
      padding: '80px',
    },
    '& p': {
      fontSize: '16px',
      lineHeight: '1.85',
      color: 'rgba(255, 255, 255, 0.72)',
      maxWidth: '540px',
      margin: '24px 0 30px',
    },
    '& .sb-button': {
      width: 'fit-content',
      maxWidth: '100%',
      minWidth: '0',
      minHeight: '52px',
      paddingInline: '23px',
      borderRadius: '10px',
      justifyContent: 'flex-start',
      gap: '12px',
      background: 'var(--sb-gold)',
      color: '#000',
      '& svg': { width: '19px', height: '19px', flex: 'none' },
    },
    '& > .sb-photo': {
      position: 'relative',
      height: '100%',
      minHeight: 'inherit',
      borderRadius: '0',
      '&::after': {
        content: '""',
        position: 'absolute',
        inset: '0',
        zIndex: '1',
        pointerEvents: 'none',
        background:
          'linear-gradient(90deg, #000 0%, rgba(0,0,0,.62) 34%, transparent 78%)',
      },
    },
    '@media (max-width: 600px)': {
      '& h2': {
        fontSize: '28px',
      },
      gridTemplateColumns: '1fr',
      gap: '0',
      minHeight: '0',
      '& > div:first-child': { padding: '80px' },
      '& > .sb-photo': {
        height: '340px',
        minHeight: '0',
      },
    },
  },
  'sb-about-grid': {
    '& h2': {
      fontWeight: '400',
      fontSize: 'clamp(32px, 3.4vw, 58px)',
      lineHeight: '1.15',
      letterSpacing: '-0.035em',
      margin: '0',
      textWrap: 'balance',
    },
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '9vw',
    paddingBlock: '110px',
    '& p': {
      fontSize: 'clamp(18px, 1.5vw, 23px)',
      lineHeight: '1.8',
      margin: '0 0 25px',
      color: '#4c4d47',
    },
    '@media (max-width: 800px)': {
      gridTemplateColumns: '1fr',
      gap: '30px',
      paddingBlock: '75px',
    },
    '@media (max-width: 600px)': {
      '& h2': {
        fontSize: '34px',
      },
    },
  },
  'sb-bottom-cta': {
    '& h2': {
      fontWeight: '400',
      fontSize: 'clamp(32px, 3.4vw, 58px)',
      lineHeight: '1.15',
      letterSpacing: '-0.035em',
      margin: '0',
      textWrap: 'balance',
    },
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '30px',
    paddingBlock: '90px',
    '@media (max-width: 600px)': {
      '& h2': {
        fontSize: '34px',
      },
      display: 'block',
      paddingBlock: '70px',
      '& .sb-button': {
        marginTop: '25px',
      },
    },
  },
  'sb-franchise-intro': {
    '& h2': {
      fontWeight: '400',
      fontSize: 'clamp(32px, 3.4vw, 58px)',
      lineHeight: '1.15',
      letterSpacing: '-0.035em',
      margin: '0',
      textWrap: 'balance',
    },
    display: 'grid',
    gridTemplateColumns: '0.75fr 1fr 1.1fr',
    gap: '5vw',
    alignItems: 'center',
    paddingBlock: '90px',
    borderBottom: '1px solid var(--sb-line)',
    '& p': {
      lineHeight: '1.8',
      color: 'var(--sb-muted)',
      fontSize: '17px',
    },
    '& > .sb-photo': {
      height: '250px',
    },
    '@media (max-width: 800px)': {
      gridTemplateColumns: '1fr',
      gap: '30px',
    },
    '@media (max-width: 600px)': {
      '& h2': {
        fontSize: '34px',
      },
      paddingBlock: '65px',
      '& > .sb-photo': {
        height: '240px',
      },
    },
  },
  'sb-apply': {
    '& h2': {
      fontWeight: '400',
      fontSize: 'clamp(32px, 3.4vw, 58px)',
      lineHeight: '1.15',
      letterSpacing: '-0.035em',
      margin: '0',
      textWrap: 'balance',
    },
    background: 'var(--sb-black)',
    color: '#fff',
    scrollMarginTop: '72px',
    '@media (max-width: 600px)': {
      '& h2': {
        fontSize: '34px',
      },
    },
  },
  'sb-contact': {
    '& h2': {
      fontWeight: '400',
      fontSize: 'clamp(32px, 3.4vw, 58px)',
      lineHeight: '1.15',
      letterSpacing: '-0.035em',
      margin: '0',
      textWrap: 'balance',
    },
    display: 'grid',
    gridTemplateColumns: '0.8fr 1.2fr',
    gap: '9vw',
    paddingBlock: '95px',
    '@media (max-width: 800px)': {
      gridTemplateColumns: '1fr',
      gap: '30px',
    },
    '@media (max-width: 600px)': {
      '& h2': {
        fontSize: '34px',
      },
      paddingBlock: '65px',
    },
  },
  'sb-menu-feature-copy': {
    padding: '80px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    '& p': {
      color: '#c7c8c1',
      fontSize: '16px',
      lineHeight: '1.8',
      maxWidth: '390px',
      margin: '25px 0 32px',
    },
    '& .sb-button': {
      width: 'fit-content',
      maxWidth: '100%',
      minWidth: '0',
      minHeight: '52px',
      paddingInline: '23px',
      borderRadius: '10px',
      justifyContent: 'flex-start',
      gap: '12px',
      '& svg': { width: '19px', height: '19px', flex: 'none' },
    },
    '@media (max-width: 800px)': {
      padding: '80px',
    },
    '@media (max-width: 600px)': {
      padding: '80px',
    },
  },
  'sb-menu-feature-mini': {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: '10px',
    padding: '24px',
    alignItems: 'stretch',
    '& > a': {
      position: 'relative',
      minWidth: '0',
      minHeight: '300px',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'flex-end',
      overflow: 'hidden',
      border: '1px solid rgba(202, 164, 94, 0.45)',
      borderRadius: '12px',
      background: '#101010',
      color: '#fff',
      transition: 'border-color 180ms ease, transform 180ms ease',
      '&::after': {
        content: '""',
        position: 'absolute',
        inset: '0',
        background:
          'linear-gradient(180deg, rgba(0,0,0,.05) 22%, rgba(0,0,0,.88) 100%)',
        pointerEvents: 'none',
      },
      '&:hover': {
        borderColor: 'rgba(222, 186, 111, 0.8)',
      },
      '&:hover .sb-photo img': { transform: 'scale(1.04)' },
    },
    '& .sb-photo': {
      position: 'absolute',
      inset: '0',
      height: '100%',
      '& img': { transition: 'transform 300ms ease' },
    },
    '& > a > span': {
      position: 'relative',
      zIndex: '1',
      padding: '15px 13px',
      color: '#fff',
      font: '600 clamp(9px, .72vw, 12px)/1.42 var(--font-inter), sans-serif',
      letterSpacing: '.13em',
    },
    '@media (max-width: 1100px)': {
      display: 'none',
    },
  },
  'sb-services-preview': {
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.28fr) minmax(360px, .72fr)',
    gridTemplateRows: 'minmax(370px, 1fr) auto',
    background: '#000',
    color: '#fff',
    border: '1px solid rgba(202, 164, 94, 0.45)',
    borderRadius: '20px',
    overflow: 'hidden',
    margin: '0 var(--sb-gutter) clamp(24px, 3vw, 42px)',
    '& > .sb-services-photo': {
      position: 'relative',
      zIndex: '0',
      minHeight: 'clamp(370px, 31vw, 540px)',
      height: '100%',
      gridColumn: '1',
      gridRow: '1',
      '& img': { objectPosition: 'center' },
      '&::after': {
        content: '""',
        position: 'absolute',
        inset: '0',
        zIndex: '1',
        pointerEvents: 'none',
        background:
          'linear-gradient(90deg, transparent 22%, rgba(0,0,0,.42) 64%, #000 100%)',
      },
    },
    '& .sb-services-intro': {
      position: 'relative',
      zIndex: '1',
      alignSelf: 'center',
      padding: '80px',
      gridColumn: '2',
      gridRow: '1',
    },
    '& .sb-services-intro h2': {
      margin: '0',
      fontWeight: '500',
      fontSize: 'clamp(28px, 2.6vw, 42px)',
      lineHeight: '1.05',
      letterSpacing: '-0.045em',
      '& span': { color: 'var(--sb-gold)' },
    },
    '& .sb-services-intro > p': {
      margin: '18px 0 26px',
      maxWidth: '480px',
      color: 'rgba(255,255,255,.72)',
      fontSize: '15px',
      lineHeight: '1.72',
    },
    '& .sb-services-benefits': {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      border: '1px solid rgba(202, 164, 94, .36)',
      borderRadius: '18px',
      overflow: 'hidden',
      '& > div': {
        minHeight: '86px',
        display: 'flex',
        alignItems: 'center',
        gap: '11px',
        padding: '15px',
        borderRight: '1px solid rgba(202, 164, 94, .24)',
        borderBottom: '1px solid rgba(202, 164, 94, .24)',
        color: 'var(--sb-gold)',
        '&:nth-of-type(2n)': { borderRight: '0' },
        '&:nth-last-of-type(-n + 2)': { borderBottom: '0' },
      },
      '& span': {
        color: '#efede6',
        fontSize: '12px',
        lineHeight: '1.45',
      },
    },
    '& .sb-ev-showcase': {
      position: 'relative',
      gridColumn: '1 / -1',
      gridRow: '2',
      minHeight: 'clamp(420px, 32vw, 560px)',
      overflow: 'hidden',
      borderTop: '1px solid rgba(202, 164, 94, .42)',
      display: 'grid',
      gridTemplateColumns: 'minmax(0, .9fr) minmax(0, 1.1fr)',
      alignItems: 'center',
      '& > .sb-photo': {
        position: 'absolute',
        inset: '0',
        height: '100%',
        opacity: '1',
        '&::after': {
          content: '""',
          position: 'absolute',
          inset: '0',
          zIndex: '1',
          pointerEvents: 'none',
          background:
            'linear-gradient(90deg, #000 0%, rgba(0,0,0,.92) 18%, rgba(0,0,0,.56) 45%, transparent 78%)',
        },
      },
    },
    '& .sb-ev-showcase-copy': {
      position: 'relative',
      zIndex: '1',
      gridColumn: '1',
      padding: '80px',
      '& h3': {
        margin: '0',
        fontWeight: '500',
        fontSize: 'clamp(28px, 2.7vw, 42px)',
        lineHeight: '1.08',
        letterSpacing: '-.045em',
        '& span': { color: 'var(--sb-gold)' },
      },
      '& p': {
        maxWidth: '440px',
        margin: '18px 0 25px',
        color: 'rgba(255,255,255,.77)',
        fontSize: '15px',
        lineHeight: '1.66',
      },
      '& .sb-button': {
        width: 'fit-content',
        maxWidth: '100%',
        minWidth: '0',
        minHeight: '52px',
        paddingInline: '23px',
        borderRadius: '10px',
        justifyContent: 'flex-start',
        gap: '12px',
        '& svg': { width: '19px', height: '19px', flex: 'none' },
      },
    },
    '& .sb-ev-showcase-points': {
      position: 'relative',
      zIndex: '1',
      gridColumn: '1 / -1',
      alignSelf: 'end',
      display: 'grid',
      gridTemplateColumns: 'repeat(3, max-content)',
      columnGap: 'clamp(32px, 5vw, 88px)',
      margin: '0 clamp(28px, 5vw, 76px) clamp(25px, 3vw, 44px)',
      '& > div': {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        padding: '0',
        color: 'var(--sb-gold)',
      },
      '& span': { color: '#eeece5', fontSize: '12px', lineHeight: '1.42' },
    },
    '@media (max-width: 800px)': {
      gridTemplateColumns: '1fr',
      gridTemplateRows: 'auto',
      '& > .sb-services-photo': {
        gridColumn: '1',
        gridRow: '1',
        minHeight: '330px',
      },
      '& .sb-services-intro': {
        gridColumn: '1',
        gridRow: '2',
        padding: '80px',
      },
      '& .sb-ev-showcase': {
        gridColumn: '1',
        gridRow: '3',
        gridTemplateColumns: '1fr',
        minHeight: '510px',
      },
      '& .sb-ev-showcase-copy': { gridColumn: '1', padding: '80px' },
      '& .sb-ev-showcase-points': {
        gridColumn: '1',
        marginInline: 'var(--sb-gutter)',
      },
    },
    '@media (max-width: 560px)': {
      '& .sb-services-benefits': {
        gridTemplateColumns: '1fr',
        '& > div': {
          borderRight: '0',
          borderBottom: '1px solid rgba(202, 164, 94, .24)',
          '&:last-child': { borderBottom: '0' },
        },
      },
      '& .sb-ev-showcase-points': {
        gridTemplateColumns: '1fr',
        '& > div': { padding: '12px 0' },
      },
    },
  },
  'sb-services-grid': {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    padding: '12px 24px 12px 0',
    margin: '0',
    alignSelf: 'center',
    '& > a': {
      display: 'block',
      minWidth: '0',
      padding: '0',
      background: '#050505',
      border: '1px solid #262626',
      transition: 'border-color 220ms ease, transform 220ms ease',
      '&:hover': {
        borderColor: 'var(--sb-gold)',
        transform: 'translateY(-4px)',
      },
    },
    '& .sb-photo': {
      height: 'clamp(160px, 13vw, 260px)',
    },
    '& > a > div:last-child': {
      padding: '18px 20px 19px',
    },
    '& h3': {
      fontSize: 'clamp(20px, 1.7vw, 29px)',
      fontWeight: '600',
      lineHeight: '1.25',
      margin: '0',
    },
    '& p': {
      fontSize: '14px',
      lineHeight: '1.55',
      color: 'rgba(255, 255, 255, 0.7)',
      margin: '9px 0 14px',
    },
    '& span': {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '10px',
      color: 'var(--sb-gold)',
      font: '500 13px/1 var(--font-kanit), sans-serif',
    },
    '& span svg': {
      width: '17px',
      height: '17px',
    },
    '@media (max-width: 600px)': {
      gridTemplateColumns: '1fr',
      gap: '12px',
      padding: '0 var(--sb-gutter) 72px',
      '& .sb-photo': {
        height: '240px',
      },
      '& h3': {
        fontSize: '21px',
      },
    },
  },
  'sb-inner-hero': {
    display: 'grid',
    gridTemplateColumns: '48% 52%',
    minHeight: '480px',
    background: '#f3f2ee',
    color: 'var(--sb-ink)',
    '& h1': {
      fontSize: 'clamp(43px, 5.2vw, 83px)',
      fontWeight: '400',
      lineHeight: '1.08',
      letterSpacing: '-0.047em',
      margin: '0',
      textWrap: 'balance',
    },
    '& p': {
      color: 'var(--sb-muted)',
      fontSize: 'clamp(16px, 1.25vw, 19px)',
      lineHeight: '1.75',
      margin: '22px 0 0',
      maxWidth: '500px',
    },
    '& > .sb-photo': {
      minHeight: '480px',
    },
    '@media (max-width: 800px)': {
      gridTemplateColumns: '1fr',
      '& > .sb-photo': {
        minHeight: '320px',
        height: '320px',
      },
    },
    '@media (max-width: 600px)': {
      '& h1': {
        fontSize: 'clamp(41px, 10vw, 60px)',
      },
      '& > .sb-photo': {
        minHeight: '260px',
        height: '260px',
      },
    },
  },
  'sb-inner-hero-dark': {
    background: 'var(--sb-black)',
    color: '#fff',
    '& p': {
      color: '#d7d8d2',
    },
  },
  'sb-inner-copy': {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '80px clamp(35px, 6vw, 110px) 80px var(--sb-gutter)',
    '@media (max-width: 800px)': {
      padding: '75px var(--sb-gutter)',
    },
    '@media (max-width: 600px)': {
      paddingBlock: '60px',
    },
  },
  'sb-about-photo': {
    '& > .sb-photo': {
      height: '500px',
    },
    '@media (max-width: 800px)': {
      '& > .sb-photo': {
        height: '370px',
      },
    },
  },
  'sb-menu-page': {
    paddingBlock: '70px 110px',
    '@media (max-width: 600px)': {
      paddingBlock: '55px 80px',
    },
  },
  'sb-branches-page': {
    paddingBlock: '70px 110px',
    '& .sb-section-heading': {
      paddingBottom: '35px',
    },
    '@media (max-width: 600px)': {
      paddingBlock: '55px 80px',
      '& .sb-section-heading': {
        paddingBottom: '30px',
      },
    },
  },
  'sb-services-page': {
    paddingBlock: '70px 110px',
    '& .sb-section-heading': {
      paddingBottom: '40px',
    },
    '@media (max-width: 600px)': {
      paddingBlock: '55px 80px',
    },
  },
  'sb-news': {
    paddingBlock: '70px 110px',
    '& .sb-section-heading': {
      paddingBottom: '30px',
    },
    '@media (max-width: 600px)': {
      paddingBlock: '55px 80px',
    },
  },
  'sb-tabs': {
    display: 'flex',
    gap: '35px',
    borderBottom: '1px solid var(--sb-line)',
    overflowX: 'auto',
    scrollbarWidth: 'none',
    '& button': {
      border: '0',
      background: 'transparent',
      color: '#71726b',
      whiteSpace: 'nowrap',
      padding: '0 0 18px',
      fontSize: '15px',
      cursor: 'pointer',
      borderBottom: '2px solid transparent',
    },
    '& button.active': {
      color: 'var(--sb-ink)',
      borderBottomColor: 'var(--sb-ink)',
      fontWeight: '600',
    },
    '@media (max-width: 600px)': {
      gap: '27px',
    },
  },
  'sb-menu-layout': {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 38%',
    gap: '9vw',
    paddingTop: '55px',
    alignItems: 'start',
    '& h2': {
      fontSize: 'clamp(36px, 4vw, 62px)',
      fontWeight: '400',
      lineHeight: '1',
      margin: '0',
    },
    '& > .sb-photo': {
      height: '650px',
    },
    '@media (max-width: 800px)': {
      gridTemplateColumns: '1fr 38%',
      gap: '35px',
      '& > .sb-photo': {
        height: '520px',
      },
    },
    '@media (max-width: 600px)': {
      gridTemplateColumns: '1fr',
      paddingTop: '35px',
      '& > .sb-photo': {
        height: '390px',
      },
    },
  },
  'sb-lead': {
    color: 'var(--sb-muted)',
    margin: '12px 0 38px',
  },
  'sb-menu-list': {
    borderTop: '1px solid var(--sb-line)',
  },
  'sb-menu-item': {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '20px',
    alignItems: 'center',
    padding: '19px 0',
    borderBottom: '1px solid var(--sb-line)',
    '& h3': {
      font: '500 clamp(19px, 1.7vw, 26px)/1.2 var(--font-inter),\n    sans-serif',
      margin: '0',
    },
    '& p': {
      color: 'var(--sb-muted)',
      fontSize: '14px',
      margin: '5px 0 0',
    },
    '& strong': {
      font: '600 17px var(--font-inter),\n    sans-serif',
    },
  },
  'sb-search': {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    border: '1px solid var(--sb-line)',
    height: '50px',
    padding: '0 15px',
    minWidth: 'min(380px, 100%)',
    '& svg': {
      width: '20px',
      height: '20px',
      color: '#777',
    },
    '& input': {
      border: '0',
      outline: '0',
      minWidth: '0',
      width: '100%',
      fontSize: '14px',
      background: 'transparent',
    },
    '&:focus-within': {
      borderColor: 'var(--sb-gold)',
    },
    '@media (max-width: 600px)': {
      marginTop: '25px',
    },
  },
  'sb-branch-list': {
    borderTop: '1px solid var(--sb-line)',
  },
  'sb-branch-row': {
    display: 'grid',
    gridTemplateColumns: '40px 200px minmax(0, 1fr) auto',
    gap: '30px',
    alignItems: 'center',
    padding: '28px 0',
    borderBottom: '1px solid var(--sb-line)',
    '& > .sb-photo': {
      height: '140px',
    },
    '@media (max-width: 1100px)': {
      gridTemplateColumns: '30px 150px minmax(0, 1fr) auto',
      gap: '18px',
    },
    '@media (max-width: 800px)': {
      gridTemplateColumns: '30px 120px minmax(0, 1fr)',
      gap: '16px',
      '& > .sb-photo': {
        height: '110px',
      },
    },
    '@media (max-width: 600px)': {
      gridTemplateColumns: '26px 1fr auto',
      gap: '12px',
      padding: '25px 0',
      '& > .sb-photo': {
        gridColumn: '2/-1',
        gridRow: '1',
        height: '190px',
      },
      '& > .sb-index': {
        gridRow: '2',
      },
    },
  },
  'sb-index': {
    font: '500 13px var(--font-inter),\n    sans-serif',
    color: '#a17d45',
    letterSpacing: '0.1em',
  },
  'sb-branch-info': {
    '& h3': {
      fontSize: 'clamp(23px, 2.2vw, 34px)',
      fontWeight: '500',
      lineHeight: '1.2',
      margin: '0 0 8px',
    },
    '& > p': {
      fontSize: '14px',
      lineHeight: '1.7',
      color: 'var(--sb-muted)',
      margin: '0',
      maxWidth: '590px',
    },
    '@media (max-width: 600px)': {
      gridColumn: '2/-1',
    },
  },
  'sb-branch-meta': {
    display: 'flex',
    gap: '20px',
    flexWrap: 'wrap',
    marginTop: '12px',
    fontSize: '13px',
    color: '#62645d',
    '& span:first-child': {
      color: '#8c713e',
    },
  },
  'sb-row-link-muted': {
    color: '#898a84',
    fontWeight: '400',
  },
  'sb-empty': {
    padding: '50px 0',
    color: 'var(--sb-muted)',
  },
  'sb-plans': {
    paddingBlock: '90px 110px',
    '@media (max-width: 600px)': {
      paddingBlock: '65px 80px',
    },
  },
  'sb-plan-grid': {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    marginTop: '50px',
    borderTop: '1px solid var(--sb-line)',
    borderLeft: '1px solid var(--sb-line)',
    '@media (max-width: 800px)': {
      gridTemplateColumns: '1fr',
    },
    '@media (max-width: 600px)': {
      marginTop: '35px',
    },
  },
  'sb-plan': {
    borderRight: '1px solid var(--sb-line)',
    borderBottom: '1px solid var(--sb-line)',
    padding: '35px',
    minHeight: '350px',
    display: 'flex',
    flexDirection: 'column',
    '& .sb-text-link': {
      alignSelf: 'flex-start',
      marginTop: 'auto',
    },
    '@media (max-width: 1100px)': {
      padding: '25px',
    },
    '@media (max-width: 800px)': {
      minHeight: 'auto',
    },
  },
  'sb-plan-top': {
    display: 'flex',
    alignItems: 'start',
    gap: '22px',
    '& > span': {
      font: '400 clamp(68px, 7vw, 110px)/0.9 Georgia,\n    serif',
      letterSpacing: '-0.07em',
    },
    '& h3': {
      fontSize: '21px',
      margin: '8px 0 3px',
      fontWeight: '500',
    },
    '& p': {
      fontSize: '13px',
      color: 'var(--sb-muted)',
      margin: '0',
    },
    '@media (max-width: 800px)': {
      '& > span': {
        fontSize: '90px',
      },
    },
  },
  'sb-plan-facts': {
    borderTop: '1px solid var(--sb-line)',
    margin: '35px 0 30px',
    '& > div': {
      display: 'flex',
      justifyContent: 'space-between',
      gap: '15px',
      borderBottom: '1px solid var(--sb-line)',
      padding: '14px 0',
      fontSize: '14px',
    },
    '& span': {
      color: 'var(--sb-muted)',
    },
    '& strong': {
      fontWeight: '600',
      textAlign: 'right',
    },
  },
  'sb-apply-layout': {
    display: 'grid',
    gridTemplateColumns: '0.8fr 1.2fr',
    gap: '9vw',
    paddingBlock: '95px',
    '& > div > p': {
      color: '#c9cbc3',
      lineHeight: '1.8',
      maxWidth: '420px',
      margin: '25px 0',
    },
    '@media (max-width: 800px)': {
      gridTemplateColumns: '1fr',
      gap: '30px',
    },
    '@media (max-width: 600px)': {
      paddingBlock: '65px',
    },
  },
  'sb-form': {
    background: '#fff',
    color: 'var(--sb-ink)',
    padding: 'clamp(26px, 3.5vw, 52px)',
    '& h3': {
      fontSize: 'clamp(25px, 2.5vw, 36px)',
      fontWeight: '500',
      margin: '0 0 30px',
    },
    '& label': {
      display: 'block',
      fontSize: '13px',
      fontWeight: '600',
    },
    '& label span': {
      color: '#a5782e',
    },
    '& input': {
      display: 'block',
      width: '100%',
      marginTop: '8px',
      border: '1px solid #d8d9d4',
      background: '#fff',
      borderRadius: '0',
      padding: '12px 14px',
      outline: '0',
      color: 'var(--sb-ink)',
      fontSize: '15px',
      fontWeight: '400',
      minHeight: '46px',
    },
    '& select': {
      display: 'block',
      width: '100%',
      marginTop: '8px',
      border: '1px solid #d8d9d4',
      background: '#fff',
      borderRadius: '0',
      padding: '12px 14px',
      outline: '0',
      color: 'var(--sb-ink)',
      fontSize: '15px',
      fontWeight: '400',
      minHeight: '46px',
    },
    '& textarea': {
      display: 'block',
      width: '100%',
      marginTop: '8px',
      border: '1px solid #d8d9d4',
      background: '#fff',
      borderRadius: '0',
      padding: '12px 14px',
      outline: '0',
      color: 'var(--sb-ink)',
      fontSize: '15px',
      fontWeight: '400',
      minHeight: '46px',
    },
    '& input:focus': {
      borderColor: 'var(--sb-gold)',
    },
    '& select:focus': {
      borderColor: 'var(--sb-gold)',
    },
    '& textarea:focus': {
      borderColor: 'var(--sb-gold)',
    },
    '& button': {
      marginTop: '30px',
    },
    '& button:disabled': {
      opacity: '0.55',
      cursor: 'wait',
    },
  },
  'sb-form-grid': {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '22px',
    '@media (max-width: 600px)': {
      gridTemplateColumns: '1fr',
      gap: '16px',
    },
  },
  'sb-form-wide': {
    gridColumn: '1/-1',
  },
  'sb-form-message': {
    color: '#35704e',
    fontSize: '14px',
    margin: '15px 0 0',
  },
  'sb-service-row': {
    display: 'grid',
    gridTemplateColumns: '48px 220px 1fr',
    gap: '35px',
    alignItems: 'center',
    borderTop: '1px solid var(--sb-line)',
    padding: '24px 0',
    '&:last-child': {
      borderBottom: '1px solid var(--sb-line)',
    },
    '& > .sb-photo': {
      height: '130px',
    },
    '& h3': {
      font: '500 clamp(26px, 3vw, 45px)/1.15 var(--font-inter),\n    sans-serif',
      letterSpacing: '-0.035em',
      margin: '0 0 9px',
    },
    '& p': {
      color: 'var(--sb-muted)',
      fontSize: '15px',
      margin: '0',
    },
    '@media (max-width: 800px)': {
      gridTemplateColumns: '40px 150px 1fr',
      gap: '20px',
    },
    '@media (max-width: 600px)': {
      gridTemplateColumns: '30px 100px 1fr',
      gap: '10px',
      padding: '18px 0',
      '& > .sb-photo': {
        height: '90px',
      },
      '& h3': {
        fontSize: '19px',
      },
      '& p': {
        fontSize: '12px',
        lineHeight: '1.45',
      },
    },
  },
  'sb-news-row': {
    display: 'grid',
    gridTemplateColumns: '55px 1fr 1fr',
    gap: '35px',
    alignItems: 'start',
    padding: '30px 0',
    borderTop: '1px solid var(--sb-line)',
    '& h3': {
      fontSize: 'clamp(22px, 2.5vw, 35px)',
      fontWeight: '400',
      lineHeight: '1.3',
      margin: '0',
    },
    '& p': {
      color: 'var(--sb-muted)',
      fontSize: '15px',
      margin: '0',
    },
    '@media (max-width: 600px)': {
      gridTemplateColumns: '35px 1fr',
      gap: '12px',
      '& p': {
        gridColumn: '2',
      },
    },
  },
  'sb-contact-info': {
    '& > p': {
      fontSize: '17px',
      lineHeight: '1.7',
      color: 'var(--sb-muted)',
      maxWidth: '400px',
    },
    '& dl': {
      marginTop: '55px',
    },
    '& dl > div': {
      padding: '16px 0',
      borderTop: '1px solid var(--sb-line)',
    },
    '& dt': {
      fontSize: '12px',
      color: '#8d763f',
      letterSpacing: '0.09em',
    },
    '& dd': {
      fontSize: '19px',
      margin: '6px 0 0',
      overflowWrap: 'anywhere',
    },
    '@media (max-width: 800px)': {
      '& dl': {
        marginTop: '30px',
      },
    },
    '@media (max-width: 600px)': {
      '& dd': {
        fontSize: '16px',
      },
    },
  },
  'sb-contact-form': {
    border: '1px solid var(--sb-line)',
    padding: '0',
  },
  'sb-legal': {
    minHeight: '58vh',
    paddingBlock: '115px 140px',
    '& h1': {
      maxWidth: '920px',
      fontSize: 'clamp(45px, 5.5vw, 84px)',
      fontWeight: '400',
      lineHeight: '1.08',
      letterSpacing: '-0.045em',
      margin: '0 0 35px',
    },
    '& p': {
      maxWidth: '700px',
      color: 'var(--sb-muted)',
      fontSize: '18px',
      lineHeight: '1.8',
    },
  },
} as const;
